name: vcserver build

on: [push, pull_request]

jobs:
  build:
    name: vcserver
    runs-on: ubuntu-latest
    container: debian:11

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install build-essential git libcurl4-gnutls-dev libasio-dev libsqlite3-dev cmake

      - name: Build libdcserver
        run: |
          cd ..
          git clone https://github.com/flyinghead/libdcserver
          cd libdcserver
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cmake --build build --config Release --target install

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Build
        run: make

      - uses: actions/upload-artifact@v4
        with:
          path: vcserver
